---
- hosts: all
  become: true
  tasks:

  - name: INSTALL APACHE2 and PHP Packages - Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: INSTALL APACHE and PHP Packages - CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

